### ISSUE TITLE
install.lua: Why set permissions to 777

### ISSUE THREAD

**Issue by jukx** [Phanx/wow-addon-updater#5]
common.lua line 324: why set the permissions to 777, default permissions should be good enough?

**Comment by Phanx** [comment]
The Battle.net app hangs on startup if it doesn't have full access to every file in the WoW directory. Chmodding to 777 avoids this problem regardless of where the files are installed, who installed them, or who's playing WoW, and has no negative effects since WoW addon files are neither secret information nor dangerous executables.
